# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='synkrino',
    version='0.1.0',
    description='Get notified when a website changes',
    python_requires='==3.*,>=3.6.0',
    author='Adam Weidner',
    license='mit',
    packages=['synkrino'],
    package_data={},
    install_requires=['requests==2.*,>=2.24.0'],
    extras_require={'dev': ['dephell==0.*,>=0.8.3']},
)
